### ISSUE TITLE
Update svelte2tsx to support destructured await

### ISSUE THREAD

**Issue by halfnelson** [sveltejs/language-tools#103]
**Describe the bug**
svelte2tsx use's svelte's parser/compiler. The AST shape for awaitblocks changed here:
https://github.com/sveltejs/svelte/commit/7d1e4e82ffb5825bee254113cbba360aea0745f0#diff-eff8bd2281855180f438ed2314a5d534
Svelte2tsx is pinned to svelte 3.16 and only supports the value:string property. We need to update to handle the de structuring now available 

**To Reproduce**
bump svelte package dependency to 3.22+ and run tests in svelte2tsx

**Comment by dummdidumm** [comment]
Mhm that's tricky because right now the svelte compiler version the user uses is tried to use. So actually we would need to support both and somehow detect the version. So that would mean no longer requiring svelte inside svelte2tsx but to provide an option to pass in svelte dynamically. Svelte2tsx would only fall back to using it's hard coded version if nothing handed in.
