### ISSUE TITLE
svelte-check is not picking up props

### ISSUE THREAD

**Issue by marks0mmers** [sveltejs/language-tools#1059]
**Describe the bug**
When running svelte-check on CLI, it is not picking up types of props when using typescript and get messages like 
`Type '{ message: string; }' is not assignable to type 'IntrinsicAttributes'`
When opening in VSCode and within IntelliSense it picks up type hints for props just fine

**To Reproduce**
1. Clone this [repo](https://github.com/marks0mmers/budget-creator-svelte)
2. Run 'yarn run check' on the CLI
3. Observer errors

**Expected behavior**
Most of the warnings should not be there

**Screenshots**
![image](https://user-images.githubusercontent.com/42284859/122567226-71152080-d016-11eb-8eb1-416edf62269b.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: Both VSCode and Webstorm
 - Plugin/Package: svelte-check

**Additional context**

**Comment by dummdidumm** [comment]
The problem is that there's a conflicting version of `svelte2tsx` installed through one of your dependencies. You have `svelte2tsx` version 0.1.x which provides conflicting global type definitions which trips up `svelte-check`. We will rewrite this so that `svelte2tsx` / `svelte-check` no longer have to rely on this kind of ambient type definitions to avoid this problem in the future. In the meantime you can force yarn to install svelte2tsx 0.2.x and the error should go away.

**Comment by marks0mmers** [comment]
Thank you! this was driving me insane
