### ISSUE TITLE
Make "Go to references" in regular JS/TS recognize uses in Svelte files

### ISSUE THREAD

**Issue by cpiber** [sveltejs/language-tools#1195]
**Is your feature request related to a problem? Please describe.**
To share functions, I put them in a .ts file. Using "Go to references" does not find uses of the functions in Svelte files.

**Describe the solution you'd like**
Supply references in Svelte files.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by jasonlyu123** [comment]
Have you tried the `svelte.enable-ts-plugin` config? this would enable a typescript plugin for "go to references" to find usage in the svelte files

**Comment by cpiber** [comment]
But that's not how finding references works. And I'm not using filesystem-based routing.

In my project, I have one `index.js`, which loads the entry point, which loads other components. Some of the components load `.ts` files and I can go to definition from there, but not back to the references.

**Comment by dummdidumm** [comment]
Could you provide a minimum reproduction repository? Or at least a few code snippets which form a minimum reproducible?

**Comment by dummdidumm** [comment]
The problem is indeed as @jasonlyu123 thought: Svelte files which are not imported in any TS file of the project don't exist for the TS server. We need to enhance the logic so that these files are somehow made known to TS. Maybe finding a way to add extra file extensions to the ts config loading behavior similar to [here](https://github.com/sveltejs/language-tools/blob/master/packages/language-server/src/plugins/typescript/service.ts#L305) can help.

**Comment by odeniso** [comment]
hello hello. has there been any progress on this? :pray:
