### ISSUE TITLE
Typescript 4.5.2 errors with svelte-check

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/language-tools#1246]
**Describe the bug**

Upgrading from "typescript": "4.4.4" to "typescript": "4.5.2" I get many many errors in my code base using `svelte-check --tsconfig ./tsconfig.json`.

Do you know this?

**Comment by dummdidumm** [comment]
This is an TypeScript issue, I created https://github.com/microsoft/TypeScript/issues/46860 for that. I also created https://github.com/sveltejs/svelte/pull/6937 which would solve this independently on our end.

**Comment by dummdidumm** [comment]
This is fixed on our end through https://github.com/sveltejs/svelte/pull/6937 . Update Svelte to the latest version and the errors should go away. Keeping this open for more visibility for others and while it's not fixed in TS itself as a reminder to wait a little before doing the next language tools release which would bumping the TS version.

**Comment by dummdidumm** [comment]
This was fixed upstream in TS 4.5.3
