### ISSUE TITLE
$$Props auto-export fields

### ISSUE THREAD

**Issue by HiiiiD** [sveltejs/language-tools#1353]
I've been developing a lot with Svelte recently and I wanted to start writing a simple component library that I can use in my projects. I've seen that there's an experimental support for $$Props for Typescript, but I think that, as of now, they're pretty much useless. I thought that by defining Prop types, all exports were added by default, sadly I found out that was not the case.

I'd like to have all the properties defined in $$Props, excluding the ones already defined, exported automatically.
For example: I have an Input component that's a simple wrapper around the ```<input />``` tag. For this reason i'd like to export every single prop of the input component, but typing it manually can take forever. Defining the type in $$Props and having the exports automatically created instead can produce a more robust and future-proof codebase.

I thought about writing a custom preprocessor that does this work for me, but idk where to start from. I think this can improve developer experience, so if anyone can tell me where to start I maybe take the preprocessor way

**Comment by dummdidumm** [comment]
Your specific use case is probably best solved with `$$props` (https://svelte.dev/docs#template-syntax-attributes-and-props)
I can see the benefit in this but it might also be very confusing that something that is type-only suddenly results in something that is compiled. It also has limitations because you can write pretty crazy type-only code which would be very hard to analyze.

**Comment by HiiiiD** [comment]
Never thought about confusion that this may cause and the limitations with crazy Typescript types analysis. Thanks
