### ISSUE TITLE
Triple reload required in VS Code after updating extension

### ISSUE THREAD

**Issue by rafrafek** [sveltejs/language-tools#1358]
**Describe the bug**
After updating Svelte for VSCode extension I have to reload VS Code 3 times.

**To Reproduce**
Update Svelte for VSCode extension.

**Expected behavior**
Single reload should be enough.

**Screenshots**
1.
![pic1](https://user-images.githubusercontent.com/23004737/151769798-685f493b-152c-41ad-be14-f60b8728cafb.png)
2.
![pic2](https://user-images.githubusercontent.com/23004737/151769826-dbf3990b-8f96-45a1-a316-4763ab08191f.png)
3.
![pic3](https://user-images.githubusercontent.com/23004737/151769851-c203b385-9060-4b29-95fe-e11c187d4951.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment]
I fear we can't change this. The problem is that it's not possible AFAIK to dynamically enable or disable a TypeScript plugin that comes with an extension. We provide a TypeScript plugin which can be enabled and is disabled by default. To provide a plugin you need to add a `typescriptServerPlugins` entry to the `package.json` of the extension. To disable it we therefore we use somewhat of a hack and add `typescriptServerPlugins-disabled` initially, and if it should be enabled, the `-disabled` part is removed. This causes the third prompt. Now every time an update is installed, the extension's `package.json` is "reset" and the `-disabled` part appears again, making the prompts show up again. We can't tell VS Code to somehow not add the `-disabled` part back.

**Comment by benignant** [comment]
Is there a downside to having the plugin enabled? Maybe it would make sense to have it enabled by default. If most people want it enabled, then it would be the minority who has to go through the triple reload.

**Comment by dummdidumm** [comment]
The plan is to enable it by default some day but I haven't gathered enough feedback yet to feel confident about it - or maybe everyone's using it and happy and I just don't know yet 😄

**Comment by dummdidumm** [comment]
Mhhhm it seems this may actually be possible: https://github.com/microsoft/vscode-typescript-tslint-plugin/issues/5 seems to implement plugin settings through VS Code settings, so if this does what I think it does we could add a setting to the plugin whether or not it should be enabled and get rid of this weird workaround.
