### ISSUE TITLE
Oddity: How does this {:catch} error type happen?

### ISSUE THREAD

**Issue by jtlapp** [sveltejs/language-tools#1364]
Under what circumstances should `{:catch err}` assign `err` a type of `never`? It is happening here:

![Screen Shot 2022-02-02 at 10 31 30](https://user-images.githubusercontent.com/138133/152200118-a81d44cb-3598-407b-91b4-c4eb6fa8d921.png)

An `external.d.ts` defines the type for `window.apis`, but the error happens regardless of whether I explicitly provide the `prepare()` return type. (This is for an Electron app.)

Svelte normally assigns `err` a type of `any`. See the tooltip:

![Screen Shot 2022-02-02 at 10 14 49](https://user-images.githubusercontent.com/138133/152200346-3a76a5a0-7108-47e4-9a83-4f285867057b.png)

**Comment by dummdidumm** [comment]
Please provide a copy-pasteable code snippet that reproduces the issue.

**Comment by dummdidumm** [comment]
Took a closer look at the image. You are missing a function call, it should be `await prepare()`, not `await prepare`. The type is `never` because you can never get into the `catch` branch, because `await prepare` will never fail because it's not a promise.

With the new transformation, this will likely still work, which is good or bad depending on how you look at this.

**Comment by jtlapp** [comment]
Oh my gosh. That fixed it. Thank you! Several folks on the Svelte discord also failed to spot this.

But shouldn't the error be on the `{#await}` rather than on an attempt to use `err`?
