### ISSUE TITLE
Basic autoCompletion not working Fine on VsCode

### ISSUE THREAD

**Issue by dolpsdw** [sveltejs/language-tools#144]
**Describe the bug**
Following tutorial on VsCode, i found autoCompletion for simple JS string not working.

**To Reproduce**
![autoCompletion](https://user-images.githubusercontent.com/4348598/83338026-734bf600-a2c0-11ea-9d79-3d366d3fb56c.gif)

**Expected behavior**
The one that happens when empty string is concatenated.

**System (please complete the following information):**
 - OS: Windows10
 - IDE: VSCode
 - Plugin/Package: "Svelte Beta"

**Comment by dolpsdw** [comment]
Not sure if this is closable.
The new behavoir still not the wanted.

As developer (specialy one new on Svelte)
I want to be able to learn by inspecting with "intellisense" and being presented with real stuff.

And the toLower case Option is not suggested until src.toLow
![autoCompletion2](https://user-images.githubusercontent.com/4348598/83410313-70631980-a416-11ea-8d88-f0c64a32cccf.gif)

**Comment by dummdidumm** [comment]
The fix will be available in about 20 hours after the next deployment. After that it will be better but you still will need to type at least one character after the dot. This cannot be changed unless the svelte compiler gets more robust, because he will throw a syntax error. This ticket tracks it https://github.com/sveltejs/svelte/issues/4818

**Comment by dolpsdw** [comment]
Not sure if it helps, but using webStorm with https://github.com/tomblachut/svelte-intellij

The autoCompletion seems to work fine.

**Comment by dummdidumm** [comment]
Yes that's true. It's unfortunate but it will hopefully not stay like this forever.
The other extension uses a different approach. I think they don't use the svelte compiler to analyze the syntax tree.

**Comment by Egnus** [comment]
I want to raise that this is still happening. Inside html context once I try to get the suggestion of a variable with a dot (.) I am getting only the available variables available at the svelte file instead of the properties that the object variable have.
This is due because the moment I put the dot notation, it breaks the file, and the suggestion cannot inspect the variables anymore in realtime.
I am guessing that disallowing the vscode to crash upon a dot notation would make the suggestion to work even when the data is still not 100% correct.
