### ISSUE TITLE
svelte props, used before assigned msg

### ISSUE THREAD

**Issue by btrauma8** [sveltejs/language-tools#146]
I'm not sure if this is bug or a known issue or i'm doing something wrong or perhaps expected behavior...but it seems like i have to give svelte props default values or it complains.

![image](https://user-images.githubusercontent.com/4399964/83357881-dd9e7e00-a334-11ea-9e91-78dd7376a11c.png)

**Comment by dummdidumm** [comment]
This is a bug, you can have inputs without default values.

**Comment by dummdidumm** [comment]
Pasting this comment from @jasonlyu123 in here from the PR which has a point:

I am kind of against suppressing used-before-assigned error because it could indeed be undefined if no value is passed in from props. People using strict mode may want the type check to be as annoying as possible, so some of the users might want to be warned if props are possibly undefined.

**Comment by dummdidumm** [comment]
Maybe we could suppress the error BUT instead update `svelte2tsx` in such a way that, in strict mode, the component interface is not typed as `Partial<{propA: .., propB: ..>` anymore but as `{propA: ..., propB: ...}`. This way you would get the erorr on the consumer side - the component which uses that other component has an error that required properties are missing. @jasonlyu123 what do you think?

**Comment by jasonlyu123** [comment]
That would be good. Act more like a function.
