### ISSUE TITLE
Question on how to debug typescript-plugin

### ISSUE THREAD

**Issue by Jojoshua** [sveltejs/language-tools#1484]
I am attempting to debug inside the typescript-plugin package, specifically inside update-imports.ts and find-references.ts

I got to the point where I am launching the VS Debugger with the 'Run VS Code Extension' configuration, my Svelte-Typescript project is opening fine but the breakpoints inside update-imports.ts or find-references.ts are still unbound (white circle instead of red). Any ideas what I am missing?

**Comment by dummdidumm** [comment]
Unfortunately, debugging the plugin is hell. Breakpoints don't work. You need to (re)start the TS server and enable logging, and then there's a command "open TS server log" or sth like that which opens a test file with all the logs. So you need to log everything you want to check. The Logger class in the plugin does this for you, also make sure to enable debug mode in it for more logs, and you can also suppress other logs in there if you want.

Closing as this isn't a real issue, but feel free to ask in here some more. Out of curiosity, what do you want to debug exactly?

**Comment by Jojoshua** [comment]
@dummdidumm thanks for the info. I was trying to figure out how https://github.com/sveltejs/language-tools/issues/1210 could be accomplished

**Comment by jasonlyu123** [comment]
There's a way to debug it. Following this doc. https://github.com/microsoft/TypeScript/wiki/Debugging-Language-Service-in-VS-Code.  Add the `TSS_DEBUG` environment variable to `Run VS Code Extension` the `launch.json` in our repo. 

```json
            "env": {
                "TSS_DEBUG": "5859"
            }
```

This way typescript's tsserver would launch in debug mode. Because most of the time, we only need to attach the debugger to the typescript plugin. We don't need to build typescript from the source like mentioned in the docs. I can create a PR to add the config to our repo later. 

But if you're interested in #1210 I don't think you need to know how to debug the typescript plugin. As it's likely can't be implemented in the typescript plugin. My initial thought is that it should be implemented in the svelte-language-server and has some custom code in the svelte-vscode. I'll leave the details in the of that issue instead.

**Comment by Jojoshua** [comment]
@jasonlyu123  @dummdidumm  Looking back at #1210 I see that perhaps there should be a distinction made so I made #1485 . As such do you still think the typescript plugin isn't the right target? Seems like update-imports.ts / find-references.ts sounds like it's already doing something in the same vein but I am not really sure which language-tool package is the best "tool" for this job.
