### ISSUE TITLE
organizeImports should use newlines between groups

### ISSUE THREAD

**Issue by seanlail** [sveltejs/language-tools#1486]
### Description

I had a look through https://github.com/sveltejs/language-tools/issues/83 and I think this has not been mentioned yet.

Currently when I save a file eslint and the svelte plugin are fighting each other.
My non-svelte files are using this plugin to sort imports:
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md

These are the rules I have:
```javascript
"import/newline-after-import": ["error", { count: 1 }],
"import/order": [
  "warn",
  {
    "newlines-between": "always",
    alphabetize: {
      order: "asc",
      caseInsensitive: true,
    },
  },
],
```

<table>
<tr>
<th>Expected</th>
<th>Actual</th>
</tr>
<tr>
<td>

```svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { writable } from "svelte/store";

  import ALib from "$lib/ALib.svelte";
  import BLib from "$lib/BLib.svelte";

  import ARelative from "./ARelative.svelte";
  import BRelative from "./BRelative.svelte";
</script>
```
</td>
<td>

```svelte
<script lang="ts">
  import ALib from "$lib/ALib.svelte";
  import BLib from "$lib/BLib.svelte";
  import { onMount } from "svelte";
  import { writable } from "svelte/store";
  import ARelative from "./ARelative.svelte";
  import BRelative from "./BRelative.svelte";
</script>
```
</td>
</tr>
</table>

### Proposed solution

Allow a way to configure this or use the eslint rules

### Alternatives

live with the Svelte files being formatted differently.

**Comment by dummdidumm** [comment]
If you say "conflict" do you mean that the formatter (a prettier plugin) conflicts with it. Does that mean you have "formatOnSave" or "organizeImports on save" turned on? What happens if you turn it off?

Btw the eslint-plugin-svelte3 is known to not play nice with some of the rules of that import plugin (but the one you mention is not listed there, who knows) https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/OTHER_PLUGINS.md

**Comment by seanlail** [comment]
@dummdidumm Yes, sorry for not being clearer. I have Code set to format on save with eslint. 

So yes, the eslint-plugin-svelte3 is conflicting with something and whatever is running last is resulting in the above format. 

I'll create a repo as soon as I can to show the issue.

**Comment by seanlail** [comment]
Here's the repo: https://github.com/seanlail/lint-format-issue

You'll notice now that if I save the `src/routes/index.svelte` file again it changes to:
```svelte
<script lang="ts">
	import ComponentA from '$component/ComponentA.svelte';
	import ComponentB from '$component/ComponentB.svelte';
	import { exampleStore } from '$component/stores';
	import { onMount } from 'svelte';
	import RelativeA from './_RelativeA.svelte';
	import RelativeB from './_RelativeB.svelte';

	onMount(() => {
		// do nothing
	});
</script>
```

**Comment by jasonlyu123** [comment]
There are some problems with your config. You didn't enable organize-import for your ts/js files. I don't know if the `source.organizeImports.eslint` command exists. Another issue is that you didn't enable eslint to validate svelte files (at least not workspace level). And it seems like you can specify the order of the codeActionsOnSave if you use an array instead of an object. 
If I change to config like this. it works as expected. 
```diff
{
-	"editor.codeActionsOnSave": {
-		"source.organizeImports.eslint": true,
-		"source.fixAll.eslint": true
-	},
+	"editor.codeActionsOnSave": ["source.organizeImports", "source.fixAll.eslint"],
	"editor.formatOnSave": true,
+	"eslint.validate": ["javascript", "typescript", "svelte"],
...
	"[svelte]": {
-		"editor.codeActionsOnSave": {
-			"source.organizeImports": true,
-			"source.fixAll": true
-		},
		"editor.defaultFormatter": "svelte.svelte-vscode",
		"editor.formatOnSave": true
	}
}

```

Group aware organize import still help in this case. Since the order of execution wouldn't matter that much. And It won't have that obvious a flash of changes because ts sort it without groups and then eslint fix it.

**Comment by seanlail** [comment]
@jasonlyu123 Thanks for the response. I really appreciate it.

I added your suggestions in this commit https://github.com/seanlail/lint-format-issue/commit/792812aa4590bdca0febdfc324b1d44c1f0d25c6 and you'll see when I saved the `/src/routes/index.svelte` file that the formatting removed the groups.

However, I found that adding the same `"editor.codeActionsOnSave": ["source.organizeImports", "source.fixAll.eslint"],` in the `[svelte]` setting fixes this and the formatting is correct. (see https://github.com/seanlail/lint-format-issue/commit/b154299473c5b2cb52306bbb8df4d4e11fb5b747)

I'm not sure if this is a bug or something that perhaps should be documented?

I can also see that it's fighting something else and "jumping around".
Hope that makes sense, video below if not.

https://user-images.githubusercontent.com/142589/169288711-800a1345-c2bd-4238-befd-3ce7f91aa42d.mov

**Comment by jasonlyu123** [comment]
Maybe you already set the config in your user settings. So you would have to override it again?

About the "fighting". this is what I meant by "flash of changes". Because of that, the group-aware organise import would still help. At least this problem won't be too obvious.
