### ISSUE TITLE
Syntax Highlight Glitch

### ISSUE THREAD

**Issue by KiddoV** [sveltejs/language-tools#1667]
### Describe the bug

Not sure what happen, but syntax highlight seem glitchy.

### Reproduction

Just editing a normal ``.svelte`` file.

### Expected behaviour

Syntax highlight looks OK.

### System Info

- OS: Windows 10
- IDE: VSCode v1.70.2
- Svelte for VS Code v106.1.1

### Additional Information, eg. Screenshots

![bug](https://user-images.githubusercontent.com/28552977/193026641-219ccc68-fac7-4b60-9e57-045034e35e48.gif)

**Comment by jasonlyu123** [comment]
If you hover over `app_logo` does it show anything? if not or only some characters work then it's very likely to be a duplicate of #1627. You can try close all the tabs in your editor and restart it to see if it persists.

**Comment by KiddoV** [comment]
> If you hover over `app_logo` does it show anything? if not or only some characters work then it's very likely to be a duplicate of #1627. You can try close all the tabs in your editor and restart it to see if it persists.
![Untitled](https://user-images.githubusercontent.com/28552977/193029194-7847fb06-e665-46b0-a410-444ab56474d1.png)

It display something but WRONG...

**Comment by KiddoV** [comment]
> Please provide a copy-pasteable code snippet that reproduces the issue for you.

I copied the ``app.svelte`` file to a separate folder, opened again with VSCode, and I didn't see that glitch anymore....

**Comment by jasonlyu123** [comment]
#1627 has to do with file casing and VSCode caching the old casing before you rename the file. Since you are in windows and you have an `app.svelte` instead of the `App.svelte` in the template. I'll assume it is the same issue. close all the tabs and restart should fix it. If the file is committed to git already, you can try `git mv` to rename the casing. Not sure why but I do encounter something before that only works after `git mv`

**Comment by KiddoV** [comment]
@jasonlyu123 Thanks for the suggestion! I close all tabs and restart VSCode, it is WORKING now.
You are right, I changed the file to lowercase this morning and the glitch start happening.
