### ISSUE TITLE
Merged prop type wrong for `svelte:component` 

### ISSUE THREAD

**Issue by oscarhermoso** [sveltejs/language-tools#1669]
### Describe the bug

`svelte:component` prop should generate type of `a | b` if rendering component `A` or `B`. However, its is incorrectly generating incompatible type `a & b`. Build succeeds, but frustrating because error cannot be ignored or dismissed with `@ts-ignore`.

```
Type 'a | b' is not assignable to type 'a & b'.
```

### Reproduction

1. Create a component with TypeScript enabled, that exports a prop with type `a`.
2. Create a second component with a prop of the same name but different type `b`.
3. Pass the props and types to a <svelte:component/> in an {#each} block.

Also created repo to reproduce here, https://github.com/oscarhermoso/ts-svelte-component-bug

See error in `ts-svelte-component-bug/src/lib/FolderComponent.svelte`

### Expected behaviour

The `<svelte:component/>` accepts prop of type `a | b`

### System Info

- OS: Pop!_OS 22.04 LTS
- IDE: VSCode  1.70.1, running extension version `svelte.svelte-vscode v106.1.1`

### Which package is the issue about?

svelte-language-server

**Comment by jasonlyu123** [comment]
I think this is expected behaviour. Because you might still have a chance to pass the wrong props. Like in your case you might be passing it like this:

```svelte
<svelte:component
	this={childData instanceof FolderData
		? FileComponent 
		: FolderComponent}
	data={childData}
/>
```

And if it's `|` you would be able to catch the error. Also, the behaviour is also the same in typescript. See the playground link. 

https://www.typescriptlang.org/play?#code/LAKFDMFcDsGMBcCWB7aACAhgI1gCgwFxoDeoa5aADgE7KUDORpIFrmR981i0A5mRQC+oQQEoSaYWBBQ4SVJiwATfEwHkadRiXVssHLj34shI8cUmgrIADYBTeGlhqTG2gxdsK+tJ259dKUE0AB8dVyp3bWYvckJfQwCIoLQAXjRqB0hqaABBaABPXFEAbmtcAHIsCrQeJwA6TQY0AH5FJTQibFhRXB7rWQQUdEz4bLzC4q7CiUEgA

**Comment by oscarhermoso** [comment]
Yeah you're 100% right, and thankyou for spending the time to help me see that @jasonlyu123
