### ISSUE TITLE
Inside a loop, the variable suggested is the array variable instead of the looping-variable

### ISSUE THREAD

**Issue by PINHOf** [sveltejs/language-tools#1735]
### Describe the bug

I'm seeing myself losing hours because of this: basically inside the `each` loop, the variable being suggested to use is the array-variable instead of the looping-variable.

Video showing the problem: https://streamable.com/5fnp02

### Reproduction

Replace **here** with `article.id`

```
{#each articles as article}
	<li>
		<Link to="../article/here">{article.title}</Link>
	</li>
{/each}
```

### Expected behaviour

Suggest the variable `article` instead of `articles`.

### System Info

- OS: Windows
- IDE: VSCode

**Comment by dummdidumm** [comment]
This is a general limitation currently - as soon as the syntax is invalid, only variables from the script tag can be suggested, because the Svelte AST can't be created. You can work around this by making the code valid through also adding the closing bracket (in your video you do `{arcticle`, to `{article}` instead)

**Comment by PINHOf** [comment]
Thanks!
