### ISSUE TITLE
Deploys are broken

### ISSUE THREAD

**Issue by orta** [sveltejs/language-tools#174]
My bad, still figuring it out, better to have an issue I can "close" when done

**Comment by dummdidumm** [comment]
Deploys are working again for npm, but for the VSCode extension there is a bug I was not able to track down yet: The node_modules folder is missing in the extension, so it will never start.

**Comment by sw-yx** [comment]
how can we help? is it a problem with orta's action or with us?

**Comment by dummdidumm** [comment]
I guess it's the actions. Since the deployment is tightly integrated with Orta's monorepo-deploy-repo, we cannot do much there right now I think.

**Comment by orta** [comment]
Hrm, it should be running npm install before each deploy - but it doesn't sound like it

**Comment by orta** [comment]
is it possible that the dependencies for svelte-vscode are wrong? This list seems very short:

```
  "devDependencies": {
        "@tsconfig/node12": "^1.0.0",
        "@types/node": "^13.9.0",
        "@types/vscode": "*",
        "typescript": "*"
    },
    "dependencies": {
        "svelte-language-server": "*",
        "vscode-languageclient": "^6.1.1"
    }
```

**Comment by dummdidumm** [comment]
Scanned the packages, the following are imported packages: `vscode`, `vscode-languageclient`, `vscode-languageserver-protocol` (although only as type, so no use at runtime), `svelte-language-server` -> the dependency list seems ok?

Even if not - it would at least still have to create a node_modules folder with those packages in it. And second, if that was the problem, why did it not fail before?

**Comment by orta** [comment]
It is [definitely running](https://github.com/sveltejs/language-tools/runs/748554609?check_suite_focus=true#step:11:286) `npm install` in the svelte-vscode` folder - so I'm interested in whether it's creating a subset of the dep tree somehow

**Comment by dummdidumm** [comment]
Yeah it's really strange. Could it go missing during the deploy step with `vsce`? Or any weird behavior because the installation is done with `npm` and the prepublish with `yarn`?

**Comment by dummdidumm** [comment]
Last deploy run now shows some npm errors about extraneous packages. All of those are from the `devDependencies`, I guess because they were installed but `npm list --production` only wants to see packages that are in `dependencies`.

If that is true, we would need to do two things:
1. add `@tsconfig/node12` under `dependencies` because it's used during build
2. the monorepo-deploy-repo needs to use `npm install --production`

**Comment by mgholam** [comment]
`package.json` has :
```js
...
	"dependencies": {
		"svelte-language-server": "file:../language-server",   // <--- file:
...
```

**Comment by dummdidumm** [comment]
Removing that rewire step from the build made the extension deploy again - thanks @mgholam for that find!
But it still does not contain the `node_modules` folder which is super strange because [the log](https://github.com/sveltejs/language-tools/runs/750654179?check_suite_focus=true#step:10:302) even says "hey that's a lot of js files".

**Comment by dummdidumm** [comment]
Got it deploying properly again. 

- commented out the "rewire `svelte-language-server` to local version" part (we can remove that I think)
- added missing `parse5` dependency to `svelte-language-server`
- re-added the prepublish build scripts
- reverted the used monorepo-deploy version to one before using `npm install --production`. @orta I think it should be reverted to `npm install`, because else all the build steps will fail ("cannot found rollup/whatever"). But we should do `npm prune --production` afterwards to at least get rid of those modules afterwards.

It's all still in a rough state which needs some cleanup, but the main problem is fixed.

**Comment by orta** [comment]
👍  thanks @dummdidumm!

**Comment by orta** [comment]
I shipped a commit first without the prune, and then another which drops the `--production` from the install to the monorepo deployer 👍

**Comment by dummdidumm** [comment]
Working regularly again.
