### ISSUE TITLE
Extension is not compatible with local prettier-plugin-svelte plugin

### ISSUE THREAD

**Issue by gukeskl** [sveltejs/language-tools#1766]
### Describe the bug

When the project `.prittierrc` contains

```json
{
   plugins: [prettier-plugin-svelte],
   (...)
}
```

the extension cant format the `.svelte` files
I know that the extension has "prettier-plugin-svelte" itself but I need the plugin to make pretty-quick work

### Reproduction

Add `prettier-plugin-svelte` to `.prittierrc` plugins

Try to format .svelte file

### Expected behaviour

extension should work with local  prettier-plugin-svelte

### System Info

- OS: Windows
- IDE:  VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment]
I can't reproduce this. Please provide more information, ideally a reproduction repository.

**Comment by jasonlyu123** [comment]
It seems to be related to #1763. Is your `.prettierrc` file in the workspace root? Or is it a mono repo setup?

**Comment by gukeskl** [comment]
> It seems to be related to #1763. Is your `.prettierrc` file in the workspace root? Or is it a mono repo setup?

Yes! You are right, thank you! 

Funny is that it works correctly when `.prettierrc` doesn't has `prettier-plugin-svelte` plugin

**Comment by jasonlyu123** [comment]
Combining both this issue and #1763. I can reproduce the incompatibility when the `plugins` in `prettierrc`

1. No local `prettier-plugin-svelte` installed 
2. `prettier-plugin-svelte` is installed in the subdirectory. 

Both failed because prettier-plugin-svelte in not in `path.join(process.cwd(), 'node_modules')`. prettier tries to load the explicitly specified plugin with `require.resolve('prettier-plugin-svelte', [ process.cwd() ])`. 

The first one failed because no prettier-plugin-svelte is installed. Ideally in this case our bundled version should kick in. But because we let prettier load both explicitly specified and then our fallback version and it failed at the explicitly specified one. In this case, we might need to do a dry run before `prettier`. And filter out the unresolvable to ensure fallback works. Or maybe we require users to remove that options. 

While the latter failed because the `process.cwd()` is where you open your editor so it can't find it. Not sure how can we fix this. Because we use a prettier API to load the config file and it doesn't seem to return where the config file so we can resolve the actual path.

**Comment by Rich-Harris** [comment]
https://github.com/sveltejs/kit/pull/8679 seems to be related to this. I've created a repro, for what it's worth: https://github.com/Rich-Harris/svelte-vscode-prettier-repro
