### ISSUE TITLE
Cannot find module (without '.svelte' extension)

### ISSUE THREAD

**Issue by vollpiin** [sveltejs/language-tools#180]
**Describe the bug**
Importing Svelte components without '.svelte' extension displays Cannot find module in vscode (using TypeScript).

Build is fine, using rollup with:

```
resolve({
      browser: true,
      extensions: [".svelte", ".ts", ".js"],
      dedupe: ["svelte"],
    }),
```

**To Reproduce**
Cf. [hbbio/svelte-ts@cf36d8a](https://github.com/hbbio/svelte-ts/commit/cf36d8a33d630b4c957dbd96a77d47c3993ff88d)

**Expected behavior**
preprocess should resolve .svelte files (in addition to .ts and .js, cf [#159](https://github.com/sveltejs/svelte-preprocess/issues/159) ).

**Information about your project:**
- svelte 3.23.0
- typescript 3.9.3
- svelte-preprocess 3.7.4
- rollup

Original Post : https://github.com/sveltejs/svelte-preprocess/issues/160

**Comment by dummdidumm** [comment]
I get this error inside a typescript file. Inside typescript files you should import the file with the extension `.svelte` at the end. If I do this, the error goes away. Since we don't analyze typescript files, only svelte files, this is out of reach of this extension right now.

By the way I suggest not using the `<script lang="typescript" src="file.ts"></script>` component style, you loose intellisense and maybe some other bugs you experience come from that.
