### ISSUE TITLE
Look into Build Server Protocol (BSP) maybe?

### ISSUE THREAD

**Issue by hackape** [sveltejs/language-tools#184]
**Is your feature request related to a problem? Please describe.**
LSP feature semantics doesn't cover compiler/build tool capability well, while BSP does. Svelte is a compiler, think it might fit.

**Describe the solution you'd like**
I open this issue just to raise awareness of the existence of BSP. Need looking into details how svelte would benefit from it. Link here: https://build-server-protocol.github.io/docs/specification

**Additional context**
I just file a PR implementing a vscode extension feature that shows compiled js code result to the side of "*.svelte" file, just like the online REPL. During the process I discovered that LSP doesn't really have semantics describing the intention like "get compiled result". I ended up using custom "$/something" message type.

**Comment by dummdidumm** [comment]
Thanks for bringing this up! I'm not sure it would help us in this context though, because the language-server currently is used to provide editors with content which suits the LSP (language server protocol). While things such as your REPL are fantastic, I don't see that we will have many of those features in the language-server package, so I think the easiest way is to just use custom events for that. Also I did not find an implementation for javascript we could use.
