### ISSUE TITLE
import type from "./" rather than "./$types"

### ISSUE THREAD

**Issue by swhoro** [sveltejs/language-tools#1854]
### Describe the bug

![image](https://user-images.githubusercontent.com/34229589/216519394-f128f675-3b15-42f8-9cf3-c2ca09aa5a88.png)

for example, I want to import pagedata from "./$types"

but when I choose the first, it becomes this:

![image](https://user-images.githubusercontent.com/34229589/216519697-b38a24e1-8c87-40c9-a0ee-a4bc4c28b18b.png)

### Reproduction

use vscode auto-complete function when importing types such as pageload

### Expected behaviour

import import type { PageData } from "./$types"

### System Info

- OS: windows 11
- IDE: vscode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
This only happens in [import statement completion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#import-statement-completions) and it's just fixed in TypeScript. We'll fix this on our side when the fix is released. In the meanwhile, you can use the normal auto import instead. 

```svelte
<script lang="ts">
export let data: PageDat/*trigger completion here*/;
</script>
```
