### ISSUE TITLE
[language-server] Support eslint -- fix

### ISSUE THREAD

**Issue by OJFord** [sveltejs/language-tools#1857]
Presently in a project that has both prettier & eslint configured, saving a file with an LSP-enabled editor will format it with prettier but not eslint.

This results in a frustrating churn, even if eslint --fix is run in a pre-commit hook say.

I think it would be a good enhancement to run eslint if such config exists.

**Comment by dummdidumm** [comment]
We won't be adding ESLint support inside the language server. You can however turn off the language server formatting with Prettier and route it through whatever eslint plugin you have, which probably has some integration of running Prettier through ESLint.
The best way in my opinion to go about this is to not run any eslint fixes that affect formatting, so that Prettier is completely in control of formatting, and eslint of other fixes. Tools like VS Code allow you to define an order in which the extensions/fixes are applied I believe.
