### ISSUE TITLE
VS Code extensions - ability to specify a custom tsconfig.ts

### ISSUE THREAD

**Issue by rallets** [sveltejs/language-tools#1869]
Hi, I'm using svelte together with another library (AngularJs, that we need slowly to replace with Svelte, but it doesn't matter for this issue) that requires a `tsconfig.ts`. 
Hence I need to use a `tsconfig.svelte.ts` and a `tsconfig.angularjs.ts` to make everything working.

In this way, however, the VS Code extension it looks to me it try to use a `default` tsconfig configuration, because it cannot pick up the custom type definitions I have setup based on: [the ufficial documentation](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-using-an-attributeevent-on-a-dom-element-and-it-throws-a-type-error) and it marks some custom DOM attributes as error.
```
Argument of type '{ "info-panel-body": boolean; }' is not assignable to parameter of type 'HTMLProps<"div", HTMLAttributes<any>>'.
  Object literal may only specify known properties, and '"info-panel-body"' does not exist in type 'HTMLProps<"div", HTMLAttributes<any>>'.ts(2345)
```

If I rename `tsconfig.svelte.ts` to `tsconfig.ts` everything then just works fine.
So I was wondering if it's possible to set a custom `tsconfig.ts` path to the Svelte VS Code extension.

I found another issue [1294](https://github.com/sveltejs/language-tools/issues/1294), but I don't thin is the same case.
Thank you in advance for any input.

**Comment by dummdidumm** [comment]
As of today, VS Code does not provide any way to specify the path to a specific `tsconfig.json` to use for intellisense. Since we try to stay close to the behavior of chore TypeScript, I don't think that we want to add such a feature (and given that the TS team [hasn't implemented it yet](https://github.com/microsoft/vscode/issues/12463) hints to me that it would be a can of worms).

If you're using `svelte-check` you can point to your specific tsconfig today by using the `--tsconfig` option

**Comment by rallets** [comment]
Tks @dummdidumm I didn't know about this limitation in vs code. It make sense, I will then wait to remove the other tsconfig.ts
