### ISSUE TITLE
Unused props are not faded (grayed/greyed out) as expected

### ISSUE THREAD

**Issue by brandonmcconnell** [sveltejs/language-tools#2014]
### Describe the bug

Any unused props are not grayed out though I would expect them to be as they are unused. You can see in the screen recording below that they do gray-out as expected if I remove the `export` keyword.

### Reproduction

(screen recording below)

### Expected behaviour

The unused props should be grayed out

### System Info

macOS v13.1
VSCode v1.78.0
Svelte for VS Code v107.4.3

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

https://github.com/sveltejs/language-tools/assets/5913254/cd66690e-b60a-4fd8-815a-d8ec78107b50

**Comment by jasonlyu123** [comment]
The reason why it's not greyed out is because it's used in the generated code behind the scenes. It's for inferring props type and invalidated control flow type set by default prop value, so we can't remove that. 

But there is also another reason why it shouldn't be greyed out. In svelte, props value can also be accessed outside the component like this.

```svelte
<script>
// Component2.svelte
export let hi = 1;
</script>
```
```svelte
<script>
	import Component2 from './Component2.svelte'
	
	let hi
	$: console.log(hi)
</script>

<Component2 bind:hi></Component2>
```

We will only know whether this prop is entirely unused if we check all the other files. In TypeScript files, the `export let ` is also not greyed out, and probably be a similar reason; you can read the value outside of the module. For this reason, I think we shouldn't report it as unnecessary and let it grey out.

**Comment by dummdidumm** [comment]
I agree with that reasoning, it's practically impossible to determine whether or not we can really gray it out, therefore closing.
