### ISSUE TITLE
Generics inside a Record

### ISSUE THREAD

**Issue by macmillen** [sveltejs/language-tools#2062]
### Describe the problem

It's not possible to use svelte generics to type nested data within a record.

As soon as I use data with a record like `{ [key: string]: { data: unknown[] } }` it types `data` as `unknown` even though it's in the extends param.

See here:

``` svelte
<script>
  // parent.svelte
  import Test from "./test.svelte";

  $: items = { asd: { label: "Lukas", data: [{ age: 29 }] } };
</script>

<Test let:item {items}>
  {item.label}
  {item.data[0]?.age}
</Test>
```

``` svelte
<script lang="ts">
  // test.svelte
  type T = $$Generic<{ [key: string]: { label: string; data: unknown[] } }>;

  export let items: T;
</script>

{#each Object.values(items) as item}
  <slot {item} />
{/each}
```

It also doesn't work when I split it up into multiple generic types: 
``` svelte
<script lang="ts">
  type U = $$Generic<any>;
  type X = $$Generic<{ label: string; data: U[] }>;
  type T = $$Generic<{ [key: string]: X }>;

  export let items: T;
</script>

{#each Object.values(items) as item}
  <slot {item} />
{/each}
```

### Describe the proposed solution

-

### Alternatives considered

-

### Importance

would make my life easier

**Comment by jasonlyu123** [comment]
I don't think we can infer this. TypeScript would infer the unwrapped item as `unknown` instead of `T`. And Similar TypeScript also infer it as `unknown`.

```ts
function* foreach<T extends unknown[]>(arr: T) {
  for (const item of arr) {
    yield item
  }
}

function unWrap<T extends unknown[]>(arr: T) {
  return arr[0]
}
```

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mAVAAmHATgUwIYQBYA8AKspgB5SZgAmAzsuANZhwDuYA2gLoB8AFNnToAXMiIBKZAG8AUAHo5yAHoB+GclQZkfCAlpRkMSgFtkcYMkHpJsjRoCeMTABtqhk+uQBfGT5mhIWAQGMAB1dGwAB2JSCio6EOY2Tl4BIVEJaU8FZTUNLCgQdDBLIQ4ABi5fIA

Alternatively, You can type it explicitly using the `$$Slots` interface.

```ts
interface $$Slots {
	default: {
		item: { label: string; data: T[] } 
	};
}
```

Or type assert it in a reactive variable.

```ts
$: values = Object.values(items) as { label: string; data: T[] }[];
```
