### ISSUE TITLE
Rect `svelte-check@3.4.5` warns about not matched dependency version if used together with `svelte@4.0.5`.

### ISSUE THREAD

**Issue by michaltaberski** [sveltejs/language-tools#2084]
### Description

```
└─┬ svelte-check 3.4.5
  └─┬ svelte-preprocess 5.0.3
    └── ✕ unmet peer svelte@^3.23.0: found 4.0.5
```

### Proposed solution

So far I didn't find problematic working with `svelte-check`, so I guess updating `package.json` to make current `svelte-check` compatible with `svelte@4.0.x` should be enough. 🤔

**Comment by dummdidumm** [comment]
The problem is the trabsigive dependency `svelte-preprocess`. There's a newer version of it with the right peer dependency, you can bump it manually yourself. I guess the package manager didn't install it because we don't specify that as the minimum version (but we use a caret so..). We should probably bump that version the next time we bump svelte-check.
