### ISSUE TITLE
Persisting Yarn PNP configuration in VCS

### ISSUE THREAD

**Issue by olafurkarl** [sveltejs/language-tools#2087]
Good day,

I've been having some trouble setting up Yarn PNP so that it works out of the box for anyone in my team that checks out our project.
Following the instructions found here works: https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#usage-with-yarn-2-pnp
However, there is a small problem which is that the `svelte.language-server.ls-path` setting can not be set on the workspace level (only the user level), which means that this is a footgun for anyone checking out the repository.

Would it be possible to make the relevant setting applied on the workspace level (in `.vscode/settings.json`), or is there a different workaround I should consider?

Thank you.

**Comment by dummdidumm** [comment]
This setting is only configurable through user setting due to security considerations. If it was configurable through workspace settings, a malicious user could point it to a file executing a virus or sth similar and everyone checking out the project would be at risk as that file would be executed as soon as the extension starts.

I'm not sure what workarounds there are. You could tell people in the readme, or have them execute a script which writes to their user settings. Either way, we will not change where this setting can be configured, so I'm closing the issue.

**Comment by olafurkarl** [comment]
Thanks @dummdidumm 
It's not really an acceptable solution regardless, as the user settings pointing to a particular project's path will only work for that specific project. It will thus only properly work for that one project, and break as soon as a dev opens a different one.

Is there any way to add better support for Yarn PNP within the plugin itself? If you point me in the right direction I'd be keen to take a look. :)
