### ISSUE TITLE
A one line change to add Emmet support in VSCode

### ISSUE THREAD

**Issue by ZYinMD** [sveltejs/language-tools#2125]
### Description

In VSCode, type something like `div.foo` in an html file, then press tab, it should expand to `<div class="foo"></div>`. This is because Emmet is built in.

I found this doesn't work in svelte files (with the `Svelte for VS Code` extension installed). However, I was able to make it work by adding this in `settings.json`:
```json
"emmet.includeLanguages": {
  "svelte": "html"
},
```
For explanation of this settings, see [this video](https://youtu.be/99JI6HY3V78) (1 min)

### Proposed solution

When user installs the VSCode extension, add `"emmet.includeLanguages": {
  "svelte": "html"
}` in settings.json.

**Comment by dummdidumm** [comment]
The VS Code extension already wraps emmet, so that shouldn't be necessary. I gotta be honest though I disabled emmet myself so not very well versed with it.

**Comment by jasonlyu123** [comment]
Can you provide a reproduction of the situation the emmet doesn't show up? This sounds like we filter out emmet because it's unreliable in some specific cases. Or maybe you disabled it through the `svelte.plugin.html.completions.emmet` config. We have emmet support in the completion form, so automatically creating a config that would create duplicate completion doesn't make sense. In some more advanced use cases (#558), it makes sense to use VSCode built-in emmet, but it doesn't seem to be the case here.

**Comment by ZYinMD** [comment]
Sorry everyone, I found the issue is on my end. I won't go into details what happened because it's unlikely to be useful for anybody else. Closing.
