### ISSUE TITLE
Double preventDefault modifier stop console.log to show on devtool

### ISSUE THREAD

**Issue by flyingduck92** [sveltejs/language-tools#2199]
### Description

To be honest I don't know where I should put this, (_bug_ or _enhancement_) so I will explain the issue that I got recently

When you have a form with `on:submit | preventDefault` with a button component that has `on:click | preventDefault` ,
the function that handles `on:submit` will not showing you the `console.log('whatever')` whenever the submit button clicked

But, if the button component that has `on:click` without `preventDefault` and a form with `on:submit | preventDefault` , it will show `console.log('whatever')` whenever the submit button clicked

- PS: I tried to upload the screenshot but it keeps saying uploading, its no end :(

### Proposed solution

Please inform that `preventDefault `should not on both side, it should applied on `on:submit` only. 
or
If the button component has `preventDefault `modifier, it should be moved to form `on:submit`

**Comment by jasonlyu123** [comment]
The problem is not double `preventDefault`. preventDefault is meant to prevent default browser behaviour. Form submission has several steps.

1 Trigger: Button clicked or Enter key pressed in an input. The click event happens here.
2. Validation: required, min, max ...etc. The invalid event happens here. 
3. Submit: Serialize the data and send out the target URL. The submit event happens here.

If you `preventDefault` on a button click, none of the later steps will even happen. That's why the submit event won't trigger. And I don't think this warning will be useful. In most cases, This will be a false positive when people actually want conditionally make a button not to be a submit button.

**Comment by flyingduck92** [comment]
> The problem is not double `preventDefault`. preventDefault is meant to prevent default browser behaviour. Form submission has several steps.
> 
> 1 Trigger: Button clicked or Enter key pressed in an input. The click, keypress event happens here. 2. Validation: required, min, max ...etc. The invalid event happens here. 3. Submit: Serialize the data and send out the target URL. The submit event happens here.
> 
> If you `preventDefault` on a button click, none of the later steps will even happen. That's why the submit event won't trigger. And I don't think this warning will be useful. In most cases, This will be a false positive when people actually want conditionally make a button not to be a submit button.

Ah, I see. I will close it this issue then
