### ISSUE TITLE
SCSS Linting not working correctly

### ISSUE THREAD

**Issue by sjafferi** [sveltejs/language-tools#227]
**Describe the bug**
My [personal site repo](https://github.com/sjafferi/sjafferi.github.io) is showing linting issues in scss style tags. It does not parse it as SCSS. I believe I have it setup properly as there aren't any errors in the command line (see repo rollup.config.js and svelte.config.js).

**To Reproduce**
Clone [personal site repo](https://github.com/sjafferi/sjafferi.github.io), go to any file with an scss style tag (say `Sun.svelte`) and observe errors. Run `yarn && yarn dev` and observe no issues in console.

**Expected behavior**
SCSS linting should work correctly

**Screenshots**
![Screen Shot 2020-06-24 at 1 56 34 PM](https://user-images.githubusercontent.com/7855859/85627234-10315300-b623-11ea-8bd9-e642721863e6.png)

**System (please complete the following information):**
 - OS: Mac OS Mojave
 - IDE: VSCode
 - Plugin/Package:  "Svelte Beta"

**Comment by dummdidumm** [comment]
In `.vscode/settings.json`, remove

```
"files.associations": {
    "*.svelte": "html"
  },
```

Because of this, the language server was never triggered to run at all.

Since you are using SCSS, make sure to follow the instructions [here](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/docs/preprocessors/scss.md), especially the node-path-thing might be relevant for you.

**Comment by sjafferi** [comment]
ahhh awesome thanks @dummdidumm !
