### ISSUE TITLE
Cannot find module '@rollup/rollup-darwin-arm64'

### ISSUE THREAD

**Issue by vorian77** [sveltejs/language-tools#2278]
### Describe the bug

VS Code crashes with: 

> Error: Cannot find module '@rollup/rollup-darwin-arm64'

### Reproduction

New Apple M3 MacBook Pro laptop using base SvelteKit with Typescript scaffolding.

<details>
  <summary>Partial output:</summary>
Initialize language server at  file:///Users/xxx/Documents/Programs/svelteTSTest
Initialize new ts service at  /Users/xxx/Documents/Programs/svelteTSTest/tsconfig.json
Trying to load configs for /Users/xxx/Documents/Programs/svelteTSTest
Error while loading config at  /Users/xxx/Documents/Programs/svelteTSTest/svelte.config.js
Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/xxx/Documents/Programs/svelteTSTest/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/Users/xxx/Documents/Programs/svelteTSTest/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js:96:48)
    ... 2 lines matching cause stack trace ...
    at Module.load (node:internal/modules/cjs/loader:1173:32)
    at node:internal/modules/cjs/loader:1014:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-arm64'
  Require stack:
  - /Users/xxx/Documents/Programs/svelteTSTest/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js
      at Function._resolveFilename (node:internal/modules/cjs/loader:1131:15)
      at node:internal/modules/cjs/loader:976:27
      at Function._load (node:electron/js2c/asar_bundle:2:13327)
      at Module.require (node:internal/modules/cjs/loader:1197:19)
      at require (node:internal/modules/cjs/helpers:121:18)
      at requireWithFriendlyError (/Users/xxx/Documents/Programs/svelteTSTest/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js:69:10)
      at Object.<anonymous> (/Users/xxx/Documents/Programs/svelteTSTest/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js:96:48)
      at Module._compile (node:internal/modules/cjs/loader:1318:14)
      at Object..js (node:internal/modules/cjs/loader:1373:10)
      at Module.load (node:internal/modules/cjs/loader:1173:32) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/xxx/Documents/Programs/svelteTSTest/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js'
    ]
  }
</details>

### Expected behaviour

Not crash on VS Code launch or when Language Server is restarted.

### System Info

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:11.933Z)
OS version: Darwin arm64 23.3.0

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
> Please try `npm i` again after removing both package-lock.json and node_modules directory.

Have you tried this?

This is most definitely not a bug on our side. The error is caused by the dependencies that you imported in the svelte.config.js. It sounds like you either copied your node_module from another machine. Or your something is running Rosetta during the installation, Maybe terminal shell or node.js installation. Can you try reinstalling the module? If just running `npm i' doesn't help, try what the error suggests. And if both don't work. Try installing it in the default terminal and check if your node.js installation is rosetta-based.

**Comment by vorian77** [comment]
Thank you for your feedback! In the big picture, it's good to know that this is a local problem.

Based on your suggestion, I created a vanilla SvelteKit project with no "svelte.config.js" file and there is no problem. 

I'm pretty new to open source development and this is my first production Svelte project. Is there anything that stands as a potential problem in my project's "svelte.config.js":

```
import adapter from '@sveltejs/adapter-auto'
// import adapter from '@sveltejs/adapter-vercel'
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	extensions: ['.svelte'],
	// Consult https://kit.svelte.dev/docs/integrations#preprocessors
	// for more information about preprocessors
	preprocess: vitePreprocess(),

	kit: {
		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
		adapter: adapter(),
		alias: {
			'$actions/*': 'src/actions/*',
			'$assets/*': 'src/lib/assets/*',
			'$comps/*': 'src/lib/components/*',
			'$dev/*': 'src/dev/*',
			'$enhance/*': 'src/lib/enhancements/*',
			'$routes/*': 'src/routes/*',
			'$server/*': 'src/lib/server/*',
			'$utils/*': 'src/lib/utils/*'
		}
	},

	vitePlugin: {
		inspector: true
	}
}

export default config

```

**Comment by vorian77** [comment]
Thanks again for your feedback!

I'm using pnpm Is the process of "reinstalling" - deleting the "node_modules" directory and the "pnpm_lock.yaml" file and then issuing the command: pnpm i? 

If so, I've tried that numerous times. If not, could you suggest more that can try?

Also, it it noteworthy that this problem doesn't occur in the WebStorm editor, only VS Code, which I was also using on the old workstation.

**Comment by jasonlyu123** [comment]
It's also likely that some part of your tool is running Rosetta, so the package manager detects that you're using x64 architecture and skipping installing the arm64 package. But your VSCode is an arm64 version, so the language server needs the arm64 variant. I don't own a Mac, so I can't help you debugging that. Maybe you might get more help in the [svelte discord](https://svelte.dev/chat).

**Comment by jasonlyu123** [comment]
Closing as resolved in a discord chat. 

https://discord.com/channels/457912077277855764/1204094017206354102

@ermincelikovic, please read through the previous comments. This is likely because the tool you used to install node.js is running Rosetta, the translation layer for running x64 software on Apple silicon. 

Check if whatever tool you used to install node.js is running in x64. If you used the installer, try downloading the Apple Arm version. If you don't know how, try reading through the thread linked above. Or search for `esbuild/darwin-arm64` there might be some similar issues you can find resources to debug.

**Comment by wvanrensburg** [comment]
I had the exact same issue, and reading through comments, I realized that my docker.compose file had a volume share between my mac and the linux docker container, therefore pushing the linux node_modules into the host, which caused these problems.

**Comment by iamabdulhaseeb** [comment]
I had same issue, I resolved my removing my node modules, package-lock.json file and reinstalled node modules.

**Comment by darckex** [comment]
worked by doing `sudo npm i` and `sudo npm run dev` after deleting node_modules and package-lock.json

**Comment by dominikg** [comment]
> worked by doing `sudo npm i` and `sudo npm run dev` after deleting node_modules and package-lock.json

for any future readers, please don't do this without educating yourself first if it is a good idea to run npm with root (spoiler: its not)

**Comment by eliseoreyes** [comment]
> I had same issue, I resolved by removing my node modules, package-lock.json file and reinstalled node modules.

Works for me! Appreciate it!

**Comment by noandersonls** [comment]
Check your node arch and that it matches your chipset, i.e.
`node -p "process.arch"`
Also if installed via brew, check brew arch too with `brew config` so it says arm64
And check which brew is running: `file $(which brew)` Maybe you'll need to uninstall the versions if they are not for the arch. Then after this, I suggest the rm -rf node_modules, cache clean and npm rebuild for your current arch!

**Comment by kass-kass** [comment]
@jasonlyu123 I realize the issue is closed, but reading through the suggested solutions, I am still confused. The (quite normal and expected in many cases) situation for me is:
1. There is a shared repository synced through git, where people work on the same Svelte/Vite project on different processor architectures and operating systems: some people on x64 Linux, some on ARM macOS
2. When running `npm install` on a project without a `package-lock.json` on any machine, one gets created with the associated native rollup specified - for example, if ran on ARM macOS, the Darwin ARM version gets installed and placed in the lockfile. The lockfile gets pushed to the repository.
3. When someone else, on a different machine and architecture (i.e. x64 Linux), is trying to use this project, and runs `npm install` or `npm ci`, this error appears:
```
Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
```
4. Now a developer on this other machine deletes the lockfile and node_modules, installs, and the other native version of rollup gets placed in the lockfile - the original macOS ARM machine will now run into the same problem.

Constantly deleting and re-installing all dependencies and re-writing the entire lockfile is clearly a silly way to do things, as it unnecessarily pollutes the commit history. Syncing the package-lock file is the 100% standard recommended approach, so just having out-of-sync lockfiles on each different machine isn't good either.

In general this also adds an extra step to just make a project build and run, for an arbitrary reason. "Was the last person who edited the project on the same OS and processor architecture as me?" is a ridiculous concern to have when simply developing a project, and becomes worse the more people work on it.

Is there no way to make this work smoothly and cross-platform?

**Comment by jasonlyu123** [comment]
@kass-kass That seems to match the linked issue in the error message. The related issue was fixed by npm earlier this year. You can try updating your npm version.

**Comment by simonh1000** [comment]
I'm seeing this in Antigravity, but not in VS Code editing the same code?!?

**Comment by bridge-jithesh** [comment]
> I'm seeing this in Antigravity, but not in VS Code editing the same code?!?

+1 on this. I don't have the issue on Zed editor either. It is so far only on AntiGravity editor.

**Comment by jasonlyu123** [comment]
For Antigravity, please see #2890 (linked just above). It's not something we can fix, but a workaround is mentioned in that issue.

I am locking this now to prevent further off-topic. If you didn't use Antigravity, but are encountering this issue. You can delete node_modules and reinstall. If it doesn't work, check if your pnpm, Node.js, or terminal app is running in x64 (Rosetta).
