### ISSUE TITLE
js single quotes

### ISSUE THREAD

**Issue by jooami** [sveltejs/language-tools#23]
Is there a way to format js with single quotes on save? They revert to double quotes when I format.

**Comment by jasonlyu123** [comment]
Svelte vscode extension use prettier to format. just config prettier to use single quote.
https://prettier.io/docs/en/configuration.html

**Comment by orta** [comment]
Yep, recommend using that!

**Comment by brgrz** [comment]
I'm seeing the same issue. I don't have Prettier installed since I had issues with it and don't actually want to use it if not absolutely neccessary. Without Prettier VS Code is reverting single quoutes inside <script> block to double qoutes even with all other VS Code settings set to single. 

```
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "svelte.svelte-vscode",
    "javascript.preferences.quoteStyle": "single",
    "typescript.preferences.quoteStyle": "single"
```

Is there anything we can do about it?

@orta @jasonlyu123

**Comment by jasonlyu123** [comment]
What I mean by "use prettier" is that it uses prettier's node API, not the prettier extension. So it doesn't matter if you have prettier extension installed. You can configure it through prettier config. Also, It's possible to configure it through `.editorconfig` now.

We didn't read the `javascript.preferences.quoteStyle` or `typescript.preferences.quoteStyle` config. So they won't have any effect on svelte file.

**Comment by jooami** [comment]
create a .prettierrc file and add { "singleQuote": true }
