### ISSUE TITLE
support svelte5

### ISSUE THREAD

**Issue by 6643** [sveltejs/language-tools#2338]
### Description

{@render children()}
Causes inability to format code

### Proposed solution

{@render children()}
Causes inability to format code

**Comment by 6643** [comment]
{#snippet abc()}
.....
{/snippet}

It can also result in an inability to format the code

**Comment by dummdidumm** [comment]
We're shipping with an earlier built-in Svelte version to support the most number of people out of the box. If you want prettier working correctly, install the latest version of `prettier` and `prettier-plugin-svelte` inside your project, then it will format correctly because the Svelte 5 parser will then be used which understand this syntax.

**Comment by jrmoynihan** [comment]
Make sure you have a `.prettierrc` file added as well!
https://github.com/sveltejs/language-tools/issues/2383#issuecomment-2168396682

**Comment by newsve** [comment]
FWIW and for others driving by:

- If you have a monorepo with several workspaces, look that `prettier` and `prettier-plugin-svelte` are installed in the root folder; I had it `thin the repo with the Svelte project which VS Code didn't find; not sure if the plugin can also look at recursive `node_modules/`
- Your .prettierrc can also be a .prettierrc.yml
