### ISSUE TITLE
Visual distinction between reactive and non-reactive Maps/Sets in editor

### ISSUE THREAD

**Issue by hanszoons** [sveltejs/language-tools#2395]
### Description

It’s too easy to forget that you need to make Sets and Maps reactive by importing them from svelte/reactivity. I’ve lost MANY hours debugging because an import was 'silently' missing: for example, moving a function that uses Map and Set from a file with reactive imports to one without.

Same goes for when you use libraries or server endpoints that return native Maps and Sets. It’s easy to forget that these are not reactive maps.

### Proposed solution

Find a way to perhaps visually distinguish between reactive and non-reactive Maps/Sets (and related) in the editor.

### Alternatives

Warn/indicate when non-reactive Maps and Sets are used or mixed with reative.

**Comment by jasonlyu123** [comment]
Closing since the reactive Map/Set has been renamed to SvelteMap and SvelteSet. In general, If you want a visual distinction between Dom API and library API with the same name. You can leverage VS Code's semantic highlighting feature if your theme supports it. Some theme already has different highlights for the default library API. Or you can add a custom config to highlight it. For example:

```json
{
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "class.defaultLibrary": {
                "underline": true
            }
        }
    },
}
```
