### ISSUE TITLE
Latest release causing types and intellisense as well as variable usages to not function correctly.

### ISSUE THREAD

**Issue by Rotinx** [sveltejs/language-tools#2419]
### Describe the bug

While using the extension types as well as intellisense and variable usages don't function so your unable to determine that a import or variable has been used or types not loading.

### Reproduction

Update to the latest release utilize in a component as you normally would. 

### Expected behaviour

Types intellisense and variable usages accurately display.

### System Info

Windows
VS Code
Extension version v108.5.2

Svelte ^4.2.17

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

Downgrading one version solved the issue.

**Comment by Rotinx** [comment]
Downgrading can be done here. Just a note for people running into this issue also.
![image](https://github.com/sveltejs/language-tools/assets/39930952/3ecdfc94-7ec9-4fa1-a657-affc430e6a36)

**Comment by jasonlyu123** [comment]
Does this happen to all the files or on a specific file? If it's a particular file, Can you recall if you have renamed the casing of a file? For example, `Test.svelte`  to `test.svelte`.

**Comment by kjk** [comment]
Happened to me too, on two different projects.

Can even repro by creating the simplest svelte javascript project with `bun create vite` (pick `svelte`, then `javascript`) .

Then open in VSCode, make an error somewhere and save the file. You should get an error immediately but you don't.

This is on latest Windows 11.

Downgrading to `108.5.1` fixed the problem.

https://github.com/sveltejs/language-tools/commit/dbfb47acde50e2b2c9bbcd864c3ffeadb06ceb5d could be the reason (just guessing, if file watching is broken then lsp won't try to re-check the files).

**Comment by kjk** [comment]
Since both me and @Rotinx are on Windows, this could be Windows only: paths and file watching is something that could break on Windows but not on Mac or Linux.

**Comment by jasonlyu123** [comment]
Please provide a reproduction that isn't bun.

**Comment by Rotinx** [comment]
> Does this happen to all the files or on a specific file? If it's a particular file, Can you recall if you have renamed the casing of a file? For example, `Test.svelte` to `test.svelte`.

It wasn't specific to only one file that's for sure. While I was developing before downgrading I was mainly in components so I cannot tell you if it also effected pages for sure. All generally components and pages are in lowercase and components with dashes test-component.svelte etc that I was working with.

I tried replicating it a few minutes ago but no luck so far.  I'll give it another go tomorrow and see if I can find a pattern.

**Comment by akb5566** [comment]
Hi, can confirm this happened to me as well. 
I didn't see any github issue opened yesterday  so I thought it was a "me problem". 
Downgrade the extension to 108.5.1 temporary fix the problem for me.

- I'm using Windows 11. 
- I'm using SvelteKit 2
- I'm using Svelte 4.2
- It happened in +page.svelte, normal-page.svelte, my-component.svelte, etc

I think the problem is v108.5.2 somehow lose its "watch file for change" ability. For example.

- I opened a file which has no syntax error. I made some error/typo on that file. The v108.5.2 extension won't show the syntax error/typo/etc.
- But if I close that file and re-open that file. The v108.5.2 extension will parse the file and show the syntax error/typo/etc.
- Same if I close VSCode and re-open VSCode. . The v108.5.2 extension will parse the file and show the syntax error/typo/etc.
- It seems like it only work when opening the file. But it dose not "watch file for change".

Unfortunately I'm working on a big collaborated project for a private company so I cannot provide a working example.

Sorry for poor English.

**Comment by jasonlyu123** [comment]
Can you check if there is any error logged in the output channel? I am on Windows and can't reproduce this error "stuck" issue. Being working on a svelte project extensively in the last two days and didn't encounter it once.

1. Ctrl+ P to open command palette
2. type Output, choose "Output: Show output channel"  and choose "svelte" in the next prompt
3. the output channel should show up near the integrated terminal

**Comment by ZelvaMan** [comment]
Hello I was having similarissue, where svelte intellisense stopped working on latest version. 
It didn't log any errors in the output. 
Downgrading to 108.5.2 fixed all my issues.
