### ISSUE TITLE
.svelte files not accepting script='ts' when being created occasionally?

### ISSUE THREAD

**Issue by orta** [sveltejs/language-tools#243]
Error: "unexpected token" in TypeScript

**Describe the bug**

![Screen Shot 2020-06-27 at 2 20 14 PM](https://user-images.githubusercontent.com/49038/85948852-107e6680-b921-11ea-9a61-54ad40f42208.png)

**To Reproduce**

I ran `npx degit dummdidumm/template svelte-typescript-app` then added a new file

It was fixable by reloading the editor

**Expected behavior**
New file being TS'd in the IDE

**Screenshots**
Above

**System (please complete the following information):**
 - OS: Mac
 - IDE: VS Code
 - Plugin/Package: Prod

**Comment by jasonlyu123** [comment]
https://github.com/sveltejs/language-tools/blob/ba274d540ecdc4fd3c48f307e805629621a33b81/packages/language-server/src/plugins/svelte/SveltePlugin.ts#L138

This is because of the caching of preprocessing config

**Comment by dummdidumm** [comment]
Why does the config cache interfere with the language detection? The language detection is done through the attributes.

**Comment by jasonlyu123** [comment]
If my understanding is correct, when you have a script tag without lang first
```
<script><script>
```
The config would be cached as don't need any fallback preprocessor.

**Comment by orta** [comment]
That fits in my head

**Comment by dummdidumm** [comment]
Oh right, I get the situation now: This can only happen if the user does not have a `svelte.config.js`, then adds the `lang="ts"`. This would fit your reproduction because my template does not have a `svelte.config.js`. 

- Solution 1: return the fallback preprocessor either way. Then this would work with `lang="ts"`. For more, the user has to add a `svelte.config.js` and then requiring the user to restart for the config to take effect is reasonable.
- Solution 2: if no config was found, try to find one each time, so don't cache anything until something is found.

Preferences?

**Comment by dummdidumm** [comment]
I dediced to go with solution 1.
