### ISSUE TITLE
VS extension Svelte for VS Code introduced errors in Version 109.00 on MacOS : absolute paths + tsconfig.json

### ISSUE THREAD

**Issue by ayaphi** [sveltejs/language-tools#2486]
### Describe the bug

(1) Svelte components imports that use absolute paths, create a `cannot find module or its corresponding type declarations ts(2307)` error in VS Code. Relative path imports work fine.

![VS Code Errors](https://github.com/user-attachments/assets/c7491c7c-312a-4da6-b20b-cddc7b38587a)

(2) Opening `tsconfig.json` creates an error message : `No svelte input files were found in config file „…/tsconfig.json“. Did you forget to add svelte files to the 'include' in your tsconfig.json? Specified 'include' paths were '["**/*.ts"]' and 'exclude' paths were ‚undefined'`

### Reproduction

Use `Svelte for VS Code` version 109.00 on MacOS 14.6.1

Downgrading to the latest version 108.6.1, everything works as expected.

### Expected behaviour

The errors should not appear - sounds silly, but that's it ;-).

### System Info

VS Code Version 1.92.2 on MacOS 14.6.1.

**Comment by dummdidumm** [comment]
Please provide a reproduction. The bare minimum would be the copy-pasted code of the file in question and your tsconfig.json.

**Comment by jasonlyu123** [comment]
This is likely similar to #2485 where the `include` config in your tsconfig.json doesn't match any svelte files and your svelte file is treated as if there isn't a tsconfig.

**Comment by bf-software** [comment]
I'm having the same issue: the new vscode extension for svelte (v109.0.0) ignores the "paths" entry in tsconfig and breaks all "non-relative" imports in my .svelte modules.   

It also introduces that error about "No svelte input files were found...".  You can satisfy that error by explicitly including at least one .svelte file in tsconfig, but although that stops the tsconfig error, it doesn't fix the broken imports in all svelte files the that use a "paths"-based, "non-relative" module import.  By the way, I shouldn't need to do this since all of my .svelte modules are imported with import statements.  (the svelte extension v108.6.1 works fine.)

[tsconfig.json](https://github.com/user-attachments/files/16917778/tsconfig.json)

```svelte
<script lang="ts">
  import AccountTree from './components/AccountTree.svelte';
  import Sizer from '@bf-s/client/components/Sizer.svelte';   // <-- Cannot find module '@bf-s/client/components/Sizer.svelte' or its corresponding type declarations.ts(2307)
  import AccountTreeToolbar from './components/AccountTreeToolbar.svelte';
  ...
```

**Comment by jasonlyu123** [comment]
It might be you just need to restart the editor after adding svelte file to the config. We can check if something can be improved. 

> I shouldn't need to do this since all of my .svelte modules are imported with import statements

We're considering about changes related to this. But having svelte file in the include is still preferred. It'll have be more consistent and performant. 

> the svelte extension v108.6.1 works fine.)

This is that the breaking change and the "no svelte input" is for. Previously svelte file is always put into the nearest tsconfig regardless for the include config.
