### ISSUE TITLE
(Svelte 5) `svelte-check` fails when project contains only `*.svelte.ts` files

### ISSUE THREAD

**Issue by peterreeves** [sveltejs/language-tools#2504]
### Describe the bug

I'm working in a mono-repo using Svelte 5 that has a utils package with only `*.svelte.ts` files. Running `svelte-check --tsconfig ./tsconfig.json` fails with the error `No svelte input files were found in config file`. However adding an empty `Thing.svelte` file to the package will fix the problem.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-gocm7l?file=package.json

Run `npm run check` and observe the `No svelte input files...` error.
Create an empty `Thing.svelte` file in the "src" folder and rerun `npm run check`.
Observe that `svelte-check` now runs, and correctly reports the problem in `src/my_file.svelte.ts`.

### Expected behaviour

`svelte-check` should run even though the package contains no `.svelte` files.

### System Info

- OS: Windows
- IDE: VsCode, StackBlitz

**Comment by jasonlyu123** [comment]
Is there any reason why you have to use svelte-check instead of tsc even though there's any svelte files?

**Comment by peterreeves** [comment]
Running vanilla `tsc` fails because one of the `.svelte.ts` files uses the `$state(...)` rune.

**Comment by jasonlyu123** [comment]
This is becuase run types are ambient types and TypeScirpt isn't aware of it. Once you import anything from svelte, it should be loaded. Or you can create any `app.d.ts` files with 

```ts
/// <reference types="svelte" />
```

**Comment by jasonlyu123** [comment]
As for the original question, the "no svelte input" error is expected. `svelte-check` is meant for svelte files so it doesn't make much sense to use svelte-check instead of tsc when you're not dealing with svelte files. svelte-check doesn't have special handling for rune, the only difference is that for typescript to understand svelte files, there is a virtual file generated and the tri slash reference comment mentioned above is in the virtual file.

**Comment by peterreeves** [comment]
Ahh, ok. Both of those solutions work for me. Thanks for your help!
