### ISSUE TITLE
VSCode: `editor.linkedEditing` does not work when the tag contains `.`

### ISSUE THREAD

**Issue by dyc3** [sveltejs/language-tools#2569]
### Describe the bug

When a tag name contains a `.` character, `linkedEditing` does not work. While it's technically invalid HTML to have non-alphanumeric characters in a tag name, the Svelte compiler accepts this as valid.

`shadcn-svelte` and `bits-ui` makes heavy use of `.` in tag names as can be seen in docs: https://www.shadcn-svelte.com/docs/components/table

### Reproduction

Steps to Reproduce:

1. Take the following sample Svelte and paste it in a blank HTML file
```svelte
<Table.Header>
	<Table.Row>
		<Table.Cell>Item</Table.Cell>
		<Table.Cell>Amount</Table.Cell>
	</Table.Row>
</Table.Header>
```
2. Enable `editor.linkedEditing`
3. Attempt to edit `Table.Row` in the start or end tag
4. See that the matching tag does not get edited

### Expected behaviour

Linked editing should allow me to edit the corresponding tag even if it contains a `.`.

### System Info

- OS: Ubuntu 20.04
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

Related: #861

I am willing to contribute a fix for this. If I could get a code pointer or two, that would be great.

**Comment by jasonlyu123** [comment]
The matching range seems to be calculated correctly but VSCode doesn't apply it. It might be because the namespaced tag doesn't match the word pattern. i.e. the regex that matches an identifier. In LSP spec you can provide an additional word pattern  https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#linkedEditingRanges You can try tweaking the existing word pattern here https://github.com/sveltejs/language-tools/blob/618053773c7355599e7d2be302816b4afbd8e733/packages/svelte-vscode/src/extension.ts#L291-L292 and add it to the linked editing result in HTMLPlugin
