### ISSUE TITLE
Component usage in a Typescript project

### ISSUE THREAD

**Issue by delucis** [sveltejs/language-tools#288]
We have a large-ish project that includes a Svelte component for in-browser debugging. We’ve been gradually migrating to Typescript, but hit a problem converting our client, because it imports the `.svelte` component file, which `tsc` doesn’t know how to handle. Is there already a way to solve this, might `svelte2tsx` be able to transform components to be compiled by `tsc`, or are there other plans for this situation? (We’re using rollup to compile the full project in case that’s relevant.)

Some links:

- [Svelte component source](https://github.com/boardgameio/boardgame.io/tree/master/src/client/debug)
- [Rollup config](https://github.com/boardgameio/boardgame.io/blob/master/rollup.config.js)

**Comment by dummdidumm** [comment]
This is probably the wrong place for this issue. This repo deals with the IDE experience and type checking experience, not bundling. You need to adjust your rollup config to deal with svelte files. Looking at the config it seems `rollup-plugin-svelte` is called after `typescript`, which is the wrong order I guess.

`svelte2tsx` is not the solution to this because `svelte2tsx` does not produce executable code, it's just internally used to provide a better IDE experience using the TypeScript language service.

**Comment by delucis** [comment]
@dummdidumm Thanks for the explanation. Sorry — I saw the `svelte2tsx` package and thought that might be relevant. I did try moving `rollup-plugin-svelte` before `typescript`, but that didn’t seem to work. I’ll keep digging!
