### ISSUE TITLE
Error when using '<' operator

### ISSUE THREAD

**Issue by jamesopstad** [sveltejs/language-tools#326]
**Describe the bug**
I've encountered an issue where VSCode shows an error saying `Type annotations can only be used in TypeScript files.`.

**To Reproduce**
This is the smallest example where I've managed to reproduce.

```svelte
<script lang='typescript'>
  let value: number = 2
  let text: string = 'hello world'
</script>

<div>
  {#if value < 3}
    <div>
      {text}
    </div>
  {/if}
</div>
```

Removing either of the divs or the `<` removes the error. It seems the the `<` operator is being interpreted as markup somehow.

**Expected behavior**
No error.

**System (please complete the following information):**
 - OS: macOS Mojave
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by jasonlyu123** [comment]
The parser we used in [extracting tag](https://github.com/sveltejs/language-tools/blob/6f3032104098de3ebbe8830a557110e8a1cb5a7c/packages/language-server/src/lib/documents/utils.ts#L63) think `< 3` is an unclosed open tag. So that it thought the script tag is inside the if block thus it doesn't know you set the lang attribute. You can copy the markup to an HTML file in vscode and try folding the div tag then you might understand I mean better. 

I would have found a way to fix it. It probably will take longer. You can workaround by moving the comparison to a function for now.
