### ISSUE TITLE
svelte-check: option to fail on warnings

### ISSUE THREAD

**Issue by AlexAegis** [sveltejs/language-tools#354]
I'd like to have a flag on svelte-check that would make it return with an exit code of 1 instead of 0 even when only warnings are encountered.

```sh
> svelte-check

Warn: 'dispatch' is declared but its value is never read. (ts)
> echo $?
0
```

```sh
> svelte-check --treat-warnings-as-errors

Warn: 'dispatch' is declared but its value is never read. (ts)
> echo $?
1
```

> I don't have a good name for this flag

**Comment by dummdidumm** [comment]
Good idea! Whether to exit with 1 or 0 is done [here](https://github.com/sveltejs/language-tools/blob/fe272d58120ab4475e75fea3feb1d47ea7f03f47/packages/svelte-check/src/index.ts#L104), which can easily be enhanced with "also exit with 1 if warnings exist and flag is et".

My proposal for the flag would be `fail-on-warnings` .

**Comment by AlexAegis** [comment]
Shouldn't some config option go along with the flag? So it's controllable for the language server as well, not just the CLI. (Don't know if it would actually be useful in that setting as it would probably be crippling during development, this option is only useful during CI, but it feels wrong to diverge the interfaces)

**Comment by dummdidumm** [comment]
I understood your request as "svelte-check should fail if there are warnings", not " convert warnings to errors". I'm a little against the latter, because the distinction is valid in my opinion. Other language services also don't have this kind of behavior. But, just like I can make tslint warnings fail my build, we should also make warnings fail the check if the user wants it. So it would not mean diverging anything, just failing earlier, warnings would still be printed as such.
