### ISSUE TITLE
Autocomplete and syntax highlighting for style attributes

### ISSUE THREAD

**Issue by techniq** [sveltejs/language-tools#381]
Coming from React/JSX, you could get the list of CSS properties within the `style` property/attribute and have syntax highlighting.

It uses object notation instead of a string, although this surprising this still shows up within a Svelte component (albeit not supported).  I figure due to the use of `svelte2tsx`

![image](https://user-images.githubusercontent.com/177476/88824053-d9a3a680-d193-11ea-86c0-cf16e51f7aa1.png)

![image](https://user-images.githubusercontent.com/177476/88824002-c0025f00-d193-11ea-96e9-80a5ff551c53.png)

It would be useful if the same was supported within Svelte when using the `style` attribute (string).

![image](https://user-images.githubusercontent.com/177476/88824098-e627ff00-d193-11ea-994f-bba202546817.png)

![image](https://user-images.githubusercontent.com/177476/88824140-f4761b00-d193-11ea-882d-88a6e05205da.png)

It would also be helpful if the expressions within the values were highlighted as such (and not just shown as one big string).

![image](https://user-images.githubusercontent.com/177476/88824274-27201380-d194-11ea-831f-ebba0c42ef2f.png)

**Comment by tanhauhau** [comment]
Reading through how this works in VSCode HTML language server, it seemed like they are using tokenizer to map out different language regions in the HTML document.

https://github.com/vscode-langservers/vscode-html-languageserver/blob/master/src/modes/embeddedSupport.ts#L26

seeing how we map out script, context script, style from the Document, it seemed like we are doing at a different approach.

i want to work on this, but i am wondering what is the recommended approach here to figure out the language mode?

**Comment by jasonlyu123** [comment]
We're currently using [vscode-html-languageserver's parser](https://github.com/microsoft/vscode-html-languageservice/blob/master/src/parser/htmlParser.ts) to do style/script tag extraction. The parser also uses the same token scanner to parse the file. so we could probably use the parsing result to get style attributes. And if there's an advantage using the token scanner maybe we could migrate to that.
After the style attributes have been extracted, the next problem is how do we handle the interpolation. With the mustache, the code is not valid CSS so the problem is how do we transform it to let CSS language service to understand it?
As for the language modes, the plugin in our codebase is similar concept. Maybe we can create another plugin for the style attributes and shared some logic with the CSS plugin.

**Comment by dummdidumm** [comment]
The syntax highlighting part will be fixed with the next release.

**Comment by jasonlyu123** [comment]
Turn out the scanning is required because the parsing result doesn't have the positioning of the attribute. I created a helper function for this in the branch for CSS class name completion for the class attribute. 

We can use it to extract the range of the style attribute value. And create another `StyleAttributeDocument` to handle position mapping. @tanhauhau still interesting in implementing this? 

And about the interpolation, maybe we should just don't provide features when we detect interpolation.

**Comment by Monkatraz** [comment]
Adding syntax highlighting inside of style strings was something I added but it was removed when it had a few issues. I don't know how the TSX grammar handles it - it's probably something goofy, like writing their own CSS syntax highlighting for just style strings.

Right now there is a hesitation to add further syntax highlighting without a test suite, but otherwise I'd be willing to experiment with this.

**Comment by techniq** [comment]
This has been resolved for a while, but forgot about this issue being open.

<img width="620" alt="CleanShot 2021-08-12 at 15 49 57@2x" src="https://user-images.githubusercontent.com/177476/129260179-cdf68f3a-f6a6-45ab-b7f7-78ca38fcdd85.png">

<img width="801" alt="CleanShot 2021-08-12 at 15 50 37@2x" src="https://user-images.githubusercontent.com/177476/129260251-a7756a7a-bb65-42d4-a563-5d4a74c821a8.png">

Thanks!
