### ISSUE TITLE
`{name}` attributes get formatted to `name="name"`

### ISSUE THREAD

**Issue by EthanThatOneKid** [sveltejs/language-tools#474]
**Describe the bug**
When formatting on save in VS Code, the `svelte.svelte-vscode` extension formats `{name}` attributes incorrectly when `.prettierrc`'s `svelteAllowShorthand` is false.

**To Reproduce**

**1. Set the prettier configuration to the following:**
```json
{
  ...,
  "svelteAllowShorthand": false,
  ...
}
```

**2. Configure the VS Code settings like so:**
```json
{
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[svelte]": {
    "editor.defaultFormatter": "svelte.svelte-vscode"
  }
}
```

**3. Use `{name}` attribute somewhere in your code like so...**
```
<!-- App.svelte -->
<Router {routes} />
```

**Expected behavior**
When shorthand is not allowed, `{name}` attributes, like in `<Router {routes} />`, are not allowed because it is considered shorthand. This has to be formatted in a non-shorthand manner, such as `<Router routes={routes} />`, but instead formats to `<Routes routes="routes" />` which is not the intention of the developer whatsoever.

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode (v1.48.1)
 - Plugin/Package: Svelte for VSCode (v101.9.3)

**Comment by dummdidumm** [comment]
This should be fixed with the latest `prettier-plugin-svelte` version (`1.2.0`) and the VSCode extension is updated to have this version built-in. If you still experience this issue, you might have a `prettier-plugin-svelte` in your workspace's `node_modules` and need to update that.

**Comment by Singha360** [comment]
This issue is still persisting on my machine:

- Ubuntu 20.04
- VSCode 1.55.0
- Svelte for VSCode v104.9.1

![image](https://user-images.githubusercontent.com/35334787/114101480-c8b74300-9893-11eb-896f-bcd8a5bd071a.png)

I couldn't find any `.pretterrc` file within my folders or the `prettier-plugin-svelte` package in `node_modules`.

I couldn't find any clue as to what's causing it to not allow me to use shorthands...

**Comment by dummdidumm** [comment]
This issue was about a specific shorthand bug, not mit being able to use shorthands in general. Did you turn on [svelteStrictMode](https://github.com/sveltejs/prettier-plugin-svelte#svelte-strict-mode)? If so that's the answer. Else I suggest to open a separate issue over at the prettier plugin svelte repo.

**Comment by Singha360** [comment]
@dummdidumm yes that was what was causing the issue:

![image](https://user-images.githubusercontent.com/35334787/114252370-c37cf580-9972-11eb-8412-387edda4f6d6.png)

Now it works fine!

Also sorry for mentioning this up on the wrong issue.
