### ISSUE TITLE
A11y is never happy when creating a <img> element

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/language-tools#524]
**Describe the bug**
I have the following image tag in my navigator that represents the current users profile picture:

`<img class="profile-picture" src="https://randomuser.me/api/portraits/women/1.jpg" alt="Your profile picture" />`

This gives me the following warning:
<img width="673" alt="8MLgUhZ7EW" src="https://user-images.githubusercontent.com/12383587/92322355-04093f00-f031-11ea-9fb4-728762a7afa3.png">
If I read it correctly it just tells me to remove the alt tag as it is obsolete. When I do so it gives me the following warning:

<img width="508" alt="djW9J2hVbb" src="https://user-images.githubusercontent.com/12383587/92322356-04a1d580-f031-11ea-9577-02be28356472.png">

**To Reproduce**
Just place down that image tag in the default Sapper template, or any other project.

**Expected behavior**
Not give me any warnings by default

**Screenshots**
See above

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VScode
 - Plugin/Package: Svelte for VScode. Sapper's default template.

**Additional context**
I don't know if this is a Sapper related thing. I don't know if this is the right place for this issue.
I've got no ESlint or type hinting configuration setup.

**Comment by dummdidumm** [comment]
This is a "bug" (or feature, depends on how you look at it) of Svelte itself, not the language-tools.

You get this warning because you use the the word "picture" in the alt tag. I think that's a warning for the case where someone writes "some picture", because that's not really a description. I doubt this behavior can/will be changed, so I suggest to just put `<!-- svelte-ignore a11y-img-redundant-alt -->` at the top of the `img` (like the quick fix would do for you).

**Comment by Gouda111** [comment]
even if you write **alt="photo"**, you will experince the same thing as screenreaders already knows it's a photo, try to add title in the alt key
