### ISSUE TITLE
Support for wider range of events

### ISSUE THREAD

**Issue by ignatiusmb** [sveltejs/language-tools#545]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but more of a concern when it's not available in the completion list. Will it work, is it supported by Svelte, that sort of concerns.

- Pointer events is not available
  ![image](https://user-images.githubusercontent.com/8156777/93479637-be008500-f926-11ea-9b02-680278f4a54d.png)
  But, it's in the list
  https://github.com/sveltejs/language-tools/blob/41827f732fb33fd29865038599a7d7ca081bb103/packages/svelte2tsx/svelte-jsx.d.ts#L177-L184

- Mouse events is not complete either, `mouseenter` and `mouseleave` is missing
  ![image](https://user-images.githubusercontent.com/8156777/93480131-4f6ff700-f927-11ea-83e0-bbf15da10e30.png)
  https://github.com/sveltejs/language-tools/blob/41827f732fb33fd29865038599a7d7ca081bb103/packages/svelte2tsx/svelte-jsx.d.ts#L157-L158

**Describe the solution you'd like**
Ideally, most events related to the element is available in the list

**Describe alternatives you've considered**
Leave it as is, it's more of a nice to have and not a must-have.

**Comment by dummdidumm** [comment]
The definitions inside `svelte-jsx` are used for typechecking. During autocompletion, they are provided as defined: `onmouseenter` instead of `on:mouseenter`. The `on:X` completions are added [here](https://github.com/sveltejs/language-tools/blob/master/packages/language-server/src/plugins/html/dataProvider.ts#L248) by enhancing the HTML language service's data provider. So to fix it, we would need to enhance that with additional global attributes.

**Comment by dummdidumm** [comment]
Added described events to the list of autocompletions. If there are others missing, feel free to open another issue.
