### ISSUE TITLE
Auto-import of component adds a new <script> tag if <script> is below markup

### ISSUE THREAD

**Issue by ItalyPaleAle** [sveltejs/language-tools#547]
**Describe the bug**
In my Svelte components, I put the `<script>` block after the markup. When I use the auto-import feature to import a new component, the language server adds a new `<script>` tag at the beginning of the file, which causes a compielr error.

**To Reproduce**

Start with this component:

```svelte
<p>Hello World!</p>
<Foo />

<script>
import Foo from './Foo.svelte'
</script>
```

After `<Foo />` type the name of another component not yet imported, such as `<Bar` then let auto-complete finish the import.

**Expected behavior**
This should appear:

```svelte
<p>Hello World!</p>
<Foo />
<Bar />

<script>
import Foo from './Foo.svelte'
import Bar from './Bar.svelte'
</script>
```

**Actual behavior**

This appears instead (which causes a compiler error because you can't have more than 1 script tag):

```svelte
<script>
import Bar from './Bar.svelte'
</script>

<p>Hello World!</p>
<Foo />
<Bar />

<script>
import Foo from './Foo.svelte'
</script>
```

**System (please complete the following information):**
 - OS: Linux
 - IDE: VS Code
 - Plugin/Package: svelte.svelte-vscode

**Comment by dummdidumm** [comment]
The problem is that, while you're in the middle of typing, the code is an error-state (unclosed tag). Because of that, everything after the unclosed-tag is treated as the child of that tag - including the top level script tag. Therefore the intellisense thinks there's no top level script tag yet and creates one. We need to investage if we can check if that tag is not closed and try to mark the children as top level so the script is recognized correctly.
