### ISSUE TITLE
Autocomplete doesn't want to use block-defined variables

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/language-tools#626]
Apologies if this has been raised previously, couldn't find an issue if so.

**Describe the bug**

VSCode wants to autocomplete the following with `things` rather than `thing`:

```svelte
<script>
  export let things = [];
</script>

{#each things as thing}
  <p>{thi...}</p>
{/each}
```

**Expected behavior**
Ideally, the locally defined variable (`thing`) would be offered as an autocomplete option, and would take priority over the array.

**Comment by dummdidumm** [comment]
This is a VS Code feature which gives suboptimal results in this case: There's the settings `editor.suggestSelection` which is set to `recentlyUsed` by default, which is why you get `things` as selected autocompletion. The `thing` autocompletion is also there, but it's one above the selected `things` selection, so it may not be visible if there are too many completions - you'd have to press the up arrow one time to select it. If you don't want that behavior, you can set `editor.suggestSelection` to `first`, then `thing` appears as the first completion as expected.
