### ISSUE TITLE
All types are stale while origin is not explicitly saved

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#636]
A type coming from any other file will be stale until that other file is saved
![Code_2020-10-26_17-52-26](https://user-images.githubusercontent.com/30108880/97202526-09267700-17b4-11eb-8c7c-cda1f72db168.png)
![Code_2020-10-26_17-52-56](https://user-images.githubusercontent.com/30108880/97202575-17749300-17b4-11eb-8f6b-4f4491e5ab1c.png)

My main concern is about the place where the extension gets the stale types from, I hope that those types being stale does not mean that the extension is running a whole duplicate typescript language server concurrent to the one vscode runs for standard `.ts` files 

That would certainly explain why svelte types are only available within `.svelte` files... Is it a misconfiguration on my part ?

**Comment by dummdidumm** [comment]
Your guess is right, it's a separate TS language server instance running. It's because it's not possible to my knowledge to add additional behavior on top of the existing TS server. There are TS plugins but those only run in the IDE, not during build, so something like `svelte-check` would not be possible. That's also why the language server only runs on Svelte files, updates from outside are not known to it unless saved to disk.

If you know ways to improve it, I'm eager to hear your suggestions.

Related: #580

**Comment by dummdidumm** [comment]
Maybe we can solve this in a way specific to the vscode extension by listening to other documentchange-events in the client and forward ts/js changes (denounced, 1 second) through a specific event to the language server. Diagnostics could be triggered afterwards, too.
