### ISSUE TITLE
`const enum` in a component always generates a runtime object

### ISSUE THREAD

**Issue by dkzlv** [sveltejs/language-tools#682]
**Describe the bug**
If you use a `const enum` in the `<script>` tag it will still generate a runtime object.

**To Reproduce**

1. use official template and run the official script for TS support
2. disable `terser` rollup plugin (to have readable output). Also, even though the default state of `preserveConstEnums` is `false`, you can set it just to be sure.
3. replace `App.svelte` contents with this:

```html
<script lang='ts'>
  const enum State {
    opened,
    closed,
  }
  let state = State.opened;
  // We add this so it is not moved into module context
  state++
</script>
```

3. run `npm build` or just look into IDE tab with the pre-built version of the component. It will look like this:

```javascript
/* generated by Svelte v3.29.7 */
import { SvelteComponent, init, safe_not_equal } from "svelte/internal";

function instance($$self) {
	var State;

	(function (State) {
		State[State["opened"] = 0] = "opened";
		State[State["closed"] = 1] = "closed";
	})(State || (State = {}));

	let state = State.opened;

	// We add this so it is not moved into module context
	state++;

	return [];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, {});
	}
}

export default Component;
```

**Expected behavior**
Should be built into something like this:

```javascript
/* generated by Svelte v3.29.7 */
import { SvelteComponent, init, safe_not_equal } from "svelte/internal";

function instance($$self) {
	let state = 0;

	// We add this so it is not moved into module context
	state++;

	return [];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, {});
	}
}

export default Component;
```

**Comment by dummdidumm** [comment]
Since this is a build error, the right place to file this would be `svelte-preprocess` since that does the TS->JS preprocessing.

The reason why this happens (I guess) is because [the tsconfig](https://github.com/tsconfig/bases/blob/master/bases/svelte.json) contains `isolatedModules: true` so that each file can be transpiled independently. `const enum` needs to know the whole project though, so using it is not possible. To not error out, TypeScript's transpilation seems to fall back to generating a regular enum.
