### ISSUE TITLE
Make TS top level errors in script explicit

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#753]
```svelte
<script lang="ts">
	declare const foo: string;
</script>
```
I was confused why this threw an error, `Modifiers cannot appear here. ts(1184)`
I didn't know but it makes sense that `declare` can only be used in the top-level

It's not self-evident for svelte users that script blocks don't accept such typescript top-level statements
maybe could the extension hint that the statement should be moved to a script context module block

Even better, a "quick fix" to move it into a script module ?

**Comment by dummdidumm** [comment]
The instance script is converted to something that is inside a function called `render`. Another solution could be to move `declare` statements outside of that function through magicstring's `move`. It needs to be checked if other intellisense features like hover info/rename still work afterwards.

**Comment by pushkine** [comment]
Moving it out would expose it in the scope of the script module, which is unexpected

**Comment by dummdidumm** [comment]
True, so we need to make the error message a little clearer. That can be added [here](https://github.com/sveltejs/language-tools/blob/master/packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts#L126), I imagine something like `if (code === 1184) { message += "If you are using a declare statement, move it into the module script block"` (Not sure what other statements need to be moved). Adding a quick fix could be done later if that happens too often, for now I'd hold off of that because of the complexity, also where to move it, people are likely to move it somewhere specific which we don't know in advance. A better alternative might be to only add a "create module script" quick fix which would only appear if that module script block does not exist yet.

**Comment by dummdidumm** [comment]
Enhanced message. Omitted the `create module script` quick fix.
