### ISSUE TITLE
SvelteSortOption config is ignored

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#764]
```
"svelte.plugin.svelte.format.config.svelteSortOrder": "options-scripts-styles-markup"
```
formatting after setting this option still uses the default (style last)

**Comment by dummdidumm** [comment]
Do you have a `.prettierrc` in your project? Do you have `prettier-plugin-svelte` in your `package.json` and if so, which version?

**Comment by dummdidumm** [comment]
Possibly related https://github.com/sveltejs/prettier-plugin-svelte/issues/193

**Comment by pushkine** [comment]
Yeah creating a `.prettierrc` makes it ignore that option
removing `.prettierrc` and restarting the language server makes it take it into account

**Comment by dummdidumm** [comment]
Do you have prettier-plugin-svelte in your package.json and if so, which version? Are you using version `104.0.0` of the extension?
What do you mean by "switches the option on/off"?

**Comment by pushkine** [comment]
I tried it in an empty project on `104.0.0`, with nothing but a `.prettierrc` and a svelte file
I do have the prettier extension 

>What do you mean by "switches the option on/off"?

whether it respects `svelte.plugin.svelte.format.config.svelteSortOrder` or formats by the default order

**Comment by dummdidumm** [comment]
If there's a `.prettierrc` present, all options of the extension are ignored. This matches Prettier's standard behavior. 
If you don't set the Svelte extension as the primary formatter for Svelte files, the options are ignored, too, because then the Prettier extension is used for formatting which knows nothing about options of other extensions. 
So I guess this is "works as designed" but we somehow have to make this more visible with some documentation.

**Comment by pushkine** [comment]
> If there's a .prettierrc present, all options of the extension are ignored

Does this mean users have to choose between a `.prettierrc` file and svelte options ?

> If you don't set the Svelte extension as the primary formatter for Svelte files [...] then the Prettier extension is used for formatting

No it's not

**Comment by dummdidumm** [comment]
> 
> 
> > If there's a .prettierrc present, all options of the extension are ignored
> 
> Does this mean users have to choose between having a `.prettierrc` file and non-default svelte options ?

No, you can just add these non-default Svelte options to your `.prettierrc` file.

> > If you don't set the Svelte extension as the primary formatter for Svelte files [...] then the Prettier extension is used for formatting
> 
> No it's not

It may depend on your user setting on what is used in which case. For example this
```
{
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```
means that the Prettier extension is used for all files. I don't know what you got in there, though, because you can also overwrite this with
```
"[svelte]": {
    "editor.defaultFormatter": "svelte.svelte-vscode"
  }
```
Then the Svelte VS Code extension is used.

**Comment by pushkine** [comment]
> No, you can just add these non-default Svelte options to your .prettierrc file

This changes everything!
`{ "svelteSortOrder": "options-scripts-styles-markup" }` in `.prettierrc` works!

**Comment by ngdangtu-vn** [comment]
I have the same problem and I'm pretty sure I only have this plugin in vscode. Please don't ask if I have `.prettierrc`. I hate it.
