### ISSUE TITLE
A CHANGELOG.md in root dir of each package?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/language-tools#913]
**Is your feature request related to a problem? Please describe.**
Is there a way to understand e.g. `svelte2tsx 0.1.183  ❯  0.1.184` improvements?

**Describe the solution you'd like**
Create a CHANGELOG.md in root dir of each package?

**Comment by dummdidumm** [comment]
Definitely makes sense. In that context I think it makes sense to switch the `svelte-language-server` and `svelte2tsx` deployments to tag-based rather than nightly. That then poses the question what to do about the nightly builds of the extensions in the vscode and openxsv marketplaces. Since they are rarely downloaded I'm inclined to just remove them.

**Comment by jasonlyu123** [comment]
Wondering if we can make nightly deploy use the `next` tag on npm.

**Comment by dummdidumm** [comment]
We'd need to add support for that in the monoreoo-deploy-nightly repo, and I'm not sure it's worth it because who will even use that? We are releasing very often anyway.

**Comment by jasonlyu123** [comment]
Yeah. Don't know if that's worth the effort. Let's only consider that if someone complains.
