### ISSUE TITLE
Keep a compiled version of tmLanguage

### ISSUE THREAD

**Issue by octref** [sveltejs/language-tools#923]
**Is your feature request related to a problem? Please describe.**
I'm the author of [shiki](https://github.com/shikijs/shiki), a library using textmate grammar to do syntax highlighting.
I used to download a copy of svelte grammar from https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/syntaxes/svelte.tmLanguage.json. Now it's no longer available.

**Describe the solution you'd like**
I only see a yml version. It'd be great if you can include a compiled JSON file there.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by dummdidumm** [comment]
We originally explictely rejected that option because it would introduce duplicated code for now obvious reason, and one would have to keep in mind to sync them up. So I'm hesitant to add this back, although it would be nice to have shiki support back in.

Since you said "we need to support yaml in the long run" in the referenced issue - what are the stop gaps currently to do that? We do it by using the `js-yaml` package which can be invoked [like this](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/package.json#L7) which transforms the yaml to a json format.

**Comment by octref** [comment]
I put a workaround on my side. Thanks for the reminder on js-yaml.
