### ISSUE TITLE
CPU load very high

### ISSUE THREAD

**Issue by blaumeise20** [sveltejs/language-tools#988]
**Describe the bug**
Same problem as #642
It only happens on a specific project if that helps you. I tried making a Sudoku solver using Svelte and Electron.

**Expected behavior**
Just don't have so much CPU load.

**System (please complete the following information):**
 - OS: MacOS
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Additional context**
I've just opened this issue to provide the CPU profiling:
[CPU-20210506T154421.cpuprofile.txt](https://github.com/sveltejs/language-tools/files/6435045/CPU-20210506T154421.cpuprofile.txt)

~~And it started to happen today. So maybe it has something to do with the current update?~~ Forget that.
I tried installing older versions but the issue still occurred. When disabling this extension it doesn't occur.

**Comment by blaumeise20** [comment]
I just found the answer: It was not a problem with the extension, I just didn't exclude `node_modules` from the tsconfig file. So make sure to always do that, otherwise you will have the same problems.

As a neat addition could the extension ignore `node_modules` itself?

**Comment by dummdidumm** [comment]
This is done right now already, but only if the tsconfig does not `"extends"` anything, which is the case for you. Moreover, this shouldn't happen anyway if your `"include"` is written in a way that files inside `node_modules` are not included. So for example if I do `"include": ["src/**/*"]` `node_modules` is not picked up because only files inside src are looked at.

Closing as the issue was resolved and there is not much we can do otherwise.
